### ISSUE TITLE
Unity Warnings (Demo Scripts exists outside the Asset folder)

### ISSUE THREAD

**Issue by Tomiha** [timcassell/ProtoPromise#146]
It is not a 'critical' issue - but rather a bit Console Polluting.
When the package is added, there are 2 warnings popping up (spawning multiple times after code changes) about some scripts (Demo/DownloadHelperExample.cs, Demo/ProtoPromiseExample.cs) that exist outside the assets folder.

![ProtoPromise_Warnings](https://user-images.githubusercontent.com/2349894/202415874-52f9babf-c584-4762-af7b-6dc586f9b19c.png)

Would it be possible to fix these minor issues?
(Maybe by adding a asmdef for the Demo folder)

I'm currently using Unity2021.3.1f1

Thanks in advance!

**Comment by timcassell** [comment]
@Tomiha Thanks for the report. Would you like to send a PR?

**Comment by timcassell** [comment]
A workaround is to import the unitypackage directly instead of using the package manager (then you can even delete the demo folder if you don't need it).
