### ISSUE TITLE
Issue with WaitForResult

### ISSUE THREAD

**Issue by Tomiha** [timcassell/ProtoPromise#167]
Hi Tim,

I've got an issue when using the WaitForResult when using it with nested promises.
I'm still investigating the issue, but I've got a promise that does multiple Http calls (internally I'm using deferred promises to get the result and state of these calls), for some reason (with the last update of your package) after the first promise gets resolved everything stops working (block the entire process). So the 'then' call of the associated first deferred promise doesn't fire anymore - stalling the process.

Again, I switched to using await for now (skipping the WaitForResult) which seems to resolve the issue. So somehow the 'WaitForResult' is bugged. And it must be related to having multiple promises during that call because I don't have this issue with a single-level promise. I know the explanation is a bit fuzzy, but just wanted to let you know maybe you are aware of it. 

Kind Regards

**Comment by timcassell** [comment]
> And it must be related to having multiple promises during that call because I don't have this issue with a single-level promise.

Well that's interesting. I can't really guess what's going on without seeing the code, however. @Tomiha

**Comment by timcassell** [comment]
@Tomiha Any update?

**Comment by timcassell** [comment]
@Tomiha I'm going to close this. If you have any further feedback, we can re-open.
