### ISSUE TITLE
Promises wrapper for Unity's AssetBundle.LoadAssetAsync()?

### ISSUE THREAD

**Issue by drew-512** [timcassell/ProtoPromise#196]
Hi,

What is the proper `Promises` invocation to wrap Unity's `AssetBundle.LoadAssetAsync()`?

When using `UnityAsync`, I was just able to call:
 ```.cs
T obj = await _assetBundle.LoadAssetAsync<T>(nameID);
```

But using `Promises` I'm unclear if there's even a convenience wrapper or what it looks like under Promises in this case.

**Comment by timcassell** [comment]
There are multiple ways you can do it. You could keep using `UnityAsync` and just wrap that await in an `async Promise<T>` function. Or you can do it just with Promises:

```cs
public static class AssetBundleHelper
{
    public static async Promise<T> LoadAssetAsync<T>(AssetBundle bundle, string nameId) where T : Object
    {
        var request = bundle.LoadAssetAsync<T>(nameId);
        await PromiseYielder.WaitFor(request);
        return request.asset as T;
    }

    public static async Promise<T> LoadAssetAsyncWithProgress<T>(AssetBundle bundle, string nameId) where T : Object
    {
        var request = bundle.LoadAssetAsync<T>(nameId);
        while (!request.isDone)
        {
            await PromiseYielder.WaitOneFrame().AwaitWithProgress(request.progress);
        }
        return request.asset as T;
    }
}
```

I didn't write any Promise wrappers for Unity-specific async operations, except I wrote a helper to convert any yieldable (in a coroutine) to a Promise via `PromiseYielder.WaitFor`. Since `AssetBundleRequest` is yieldable, it works for it.

I wanted to show an example for canceling the async operation, but it appears that API does not support aborts. For abortable operations, you can take a look at the [Demo](https://github.com/timcassell/ProtoPromise/blob/cb2b69ed4991ab21d5e3a481433914aea69b7859/ProtoPromise_Unity/Assets/Plugins/ProtoPromise/Demo/DownloadHelperExample.cs) for an example.

**Comment by timcassell** [comment]
I took a look at the `UnityAsync` library, and while it looks abandoned, it should work well with `ProtoPromise`. They do some optimization tricks that I didn't do in my `PromiseYielder` (I pool some objects, but I call `StartCoroutine` under the hood, which allocates). I think that should be fine to use until Unity has updated their APIs for async/await goodness (2023).

**Comment by drew-512** [comment]
Ok great -- and like that you totally checked it out and looked hard at it.  Your comments are super helpful thank you.

**Comment by drew-512** [comment]
I'm shooting for the "ProtoPromise pure certified" logo seal thing.  I hear there's a full gift bag.

**Comment by drew-512** [comment]
>  I think that should be fine to use until Unity has updated their APIs for async/await goodness (2023).

Have they said that's coming?  They seem to be behind on a lot and the internal downsizing can't be helping.  

Sad they are not dialing up engineering investment more considering that signs point to in ~5 years the platforms of choice will be Unity and Unreal (or what becomes of Unreal when part of Tangent is sold or otherwise acquired to make it "safe" for U.S. consumption) -- not the native OSes.

I digress, but I do think that makes a ProtoPromise a great candidate for long term success.

Best,
Drew

**Comment by timcassell** [comment]
> > I think that should be fine to use until Unity has updated their APIs for async/await goodness (2023).
> 
> Have they said that's coming?

It's already done in the pre-release. https://docs.unity3d.com/2023.1/Documentation/ScriptReference/Awaitable.html

**Comment by timcassell** [comment]
Since Unity did such a terrible job of it, I think I'll add more optimized `PromiseYielder` functions for common Unity awaits (`WaitFrames(int)`, `WaitFor(TimeSpan)`, `WaitFor(AsyncOperation)`, `WaitForFixedUpdate`). That way you won't have to rely on `UnityAsync` for optimal efficiency.

**Comment by drew-512** [comment]
So strange and sad they are so careless about that stuff. 

Psyched you're on the case!
