### ISSUE TITLE
PromiseBehaviour warning when not reloading domain

### ISSUE THREAD

**Issue by drew-512** [timcassell/ProtoPromise#204]
Hi,

When I enable **Settings > Editor > Enter Play Mode**, I get this msg:
`There can only be one instance of PromiseBehaviour. Destroying new instance`

I suspect this is expected behavior given the nature of the setting but worth raising for those who are OCD about warnings.

**Comment by timcassell** [comment]
More context: https://github.com/timcassell/ProtoPromise/commit/bfaa23ba1f9948e5b62b3532e5c1a69d217a5842#commitcomment-107851916

**Comment by timcassell** [comment]
Looks like disabling domain reloads is the cause. That's a new feature I wasn't aware of. https://docs.unity3d.com/Manual/ConfigurableEnterPlayMode.html
