### ISSUE TITLE
Fatal error when building macOS player

### ISSUE THREAD

**Issue by drew-512** [timcassell/ProtoPromise#284]
![Screen Shot 2023-10-20 at 7 21 59 PM](https://github.com/timcassell/ProtoPromise/assets/35852900/ed912d83-4204-4ddb-8d1f-21a9242101b6)

**Comment by timcassell** [comment]
That's surprising. That error only shows up in the build and not in editor?

**Comment by drew-512** [comment]
Lovely, thank you sir!

**Comment by timcassell** [comment]
@drew-512 Thanks for the report! The fix is out in v2.6.1. I also fixed the CI workflow so it should catch things like this in the future.
